use std::{
	collections::HashMap,
	fmt::Display,
	io::{Cursor, Read},
	str::FromStr
};

use discrim::FromDiscriminant;
use hitman_commons::{
	game::GameVersion,
	metadata::{ReferenceFlags, ReferenceType, ResourceMetadata, ResourceReference, RuntimeID}
};
use indexmap::IndexMap;
use strum::EnumString;
use thiserror::Error;
use tryvial::try_fn;

#[cfg(feature = "rune")]
pub fn rune_module() -> Result<rune::Module, rune::ContextError> {
	let mut module = rune::Module::with_crate_item("hitman_formats", ["sdef"])?;

	module.ty::<SdefError>()?;
	module.ty::<SoundDefinitions>()?;
	module.ty::<SoundDefinition>()?;

	Ok(module)
}

type Result<T, E = SdefError> = std::result::Result<T, E>;

#[derive(Error, Debug)]
#[cfg_attr(feature = "rune", derive(better_rune_derive::Any))]
#[cfg_attr(feature = "rune", rune(item = ::hitman_formats::sdef))]
#[cfg_attr(feature = "rune", rune_derive(DISPLAY_FMT, DEBUG_FMT))]
pub enum SdefError {
	#[error("seek error: {0}")]
	Seek(#[from] std::io::Error),

	#[error("invalid number: {0}")]
	InvalidNumber(#[from] std::num::TryFromIntError),

	#[error("no such dependency index: {0}")]
	InvalidDependency(usize),

	#[error("unrecognised sound definition: {0}")]
	InvalidSoundDefinition(u16)
}

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Clone, Debug, PartialEq)]
#[cfg_attr(feature = "rune", derive(better_rune_derive::Any))]
#[cfg_attr(feature = "rune", rune(item = ::hitman_formats::sdef))]
#[cfg_attr(feature = "rune", rune_derive(DEBUG_FMT, PARTIAL_EQ, CLONE))]
#[cfg_attr(feature = "rune", rune_functions(Self::parse__meta, Self::generate__meta))]
#[cfg_attr(feature = "rune", rune(install_with = Self::rune_install))]
#[cfg_attr(feature = "rune", rune(constructor_fn = Self::rune_construct))]
pub struct SoundDefinitions {
	#[cfg_attr(feature = "rune", rune(get, set))]
	pub id: RuntimeID,

	pub definitions: IndexMap<SoundDefinition, Option<RuntimeID>>
}

#[cfg(feature = "rune")]
impl SoundDefinitions {
	fn rune_construct(id: RuntimeID, definitions: HashMap<String, Option<RuntimeID>>) -> Self {
		Self {
			id,
			definitions: definitions
				.into_iter()
				.filter_map(|(k, v)| Some((SoundDefinition::from_str(&k).ok()?, v)))
				.collect()
		}
	}

	fn rune_install(module: &mut rune::Module) -> Result<(), rune::ContextError> {
		module.field_function(&rune::runtime::Protocol::GET, "definitions", |s: &Self| {
			s.definitions
				.iter()
				.map(|(k, v)| (k.to_string(), v.to_owned()))
				.collect::<HashMap<_, _>>()
		})?;

		module.field_function(
			&rune::runtime::Protocol::SET,
			"definitions",
			|s: &mut Self, definitions: HashMap<String, Option<RuntimeID>>| {
				s.definitions = definitions
					.into_iter()
					.filter_map(|(k, v)| Some((SoundDefinition::from_str(&k).ok()?, v)))
					.collect();
			}
		)?;

		Ok(())
	}
}

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, FromDiscriminant, EnumString)]
#[cfg_attr(feature = "rune", serde_with::apply(_ => #[rune(get, set)]))]
#[cfg_attr(feature = "rune", derive(better_rune_derive::Any))]
#[cfg_attr(feature = "rune", rune(item = ::hitman_formats::sdef))]
#[cfg_attr(feature = "rune", rune_derive(DISPLAY_FMT, DEBUG_FMT, PARTIAL_EQ, EQ, CLONE))]
#[cfg_attr(
	feature = "rune",
	rune_functions(
		Self::from_h3_discriminant__meta,
		Self::from_h2_discriminant__meta,
		Self::from_h1_discriminant__meta,
		Self::as_h3_discriminant__meta,
		Self::as_h2_discriminant__meta,
		Self::as_h1_discriminant__meta
	)
)]
#[repr(u16)]
pub enum SoundDefinition {
	_NoSound,
	Dth_BrkNck,
	Dth_Fll,
	Dth_GnSht,
	Dth_HdSht,
	Dth_Mpct,
	Dth_SltThrt,
	Dth_Strngl,
	Dth_Xplo,
	Dth_PrpF,
	Dth_Electro,
	Dth_Burn,
	Dth_Crush,
	Dth_Scrm,
	Dth_Hrt,
	Dth_SrpsGrab,
	Dth_HumShldStrain,
	Dth_Snore,
	Dth_Groan,
	Dth_Dump,
	Dth_PrpTssFrntAck,
	Dth_Headlock,
	Dth_Blinded,
	Dth_BeeSting,
	Dth_Grab,
	Gen_Grt47,
	Gen_GrtGrd47WGun,
	Gen_GrtTrgt,
	Gen_GrtTrgtRsp,
	Gen_NPC2NPCGrt,
	Gen_NPC2NPCRsp,
	Gen_GtHlp,
	Gen_GtHlpLd,
	Gen_GtHlp47Knwn,
	Gen_Mssng,
	Gen_HMHere,
	Gen_HMThere,
	Gen_SrpsLow,
	Gen_SrpsLowShort,
	Gen_Srps,
	Gen_SrpsLd,
	Gen_StndRsp,
	Gen_Stop,
	Gen_StopLd,
	Gen_Reveal,
	Gen_ThumbsUp,
	Gen_BrknAck,
	Gen_Ack,
	Gen_AckLd,
	Gen_AckNtnse,
	Gen_BumpAck,
	Gen_Curse,
	Gen_CurseLow,
	Gen_DrpGun,
	Gen_DrpCase,
	Gen_CoinCurse,
	Gen_TransportGreet,
	Gen_Thanks,
	Gen_ReturnItem2Guard,
	Gen_NoWay1,
	Gen_NoWay2Kidding,
	Gen_NoWay3Joke,
	Gen_NoWay44Real,
	Gen_NoWay5DntBeliv,
	Gen_NoWay6Serious,
	Gen_NoWay7Horrible,
	Gen_Way1,
	Gen_Way2Kidding,
	Gen_Way3Joke,
	Gen_Way44Real,
	Gen_Way5DntBeliv,
	Gen_Way6Serious,
	Gen_Way7Horrible,
	Gen_NkdRunAck,
	Gen_Grasp,
	Gen_Amused,
	Gen_Annoyed,
	Gen_BdygrdArrive,
	Gen_BdygrdMovOut,
	Gen_GiveUp,
	Gen_Off,
	Gen_On,
	Gen_PanicLow,
	Gen_Sick,
	Gen_SmellAck,
	Gen_SmrtPhnAct,
	Gen_PhoneAct,
	Gen_OutbreakInfect,
	Gen_OutbreakSick,
	Gen_OutbreakWhine,
	Gtag,
	ClsCmbt_Ack,
	ClsCmbt_Tnt,
	Cmbt_BackupCll,
	Cmbt_BadDsg,
	Cmbt_Beg,
	Cmbt_ClsAck,
	Cmbt_Fire,
	Cmbt_FireLdr,
	Cmbt_GtHit,
	Cmbt_HitHM,
	Cmbt_HMClsCmbtAck,
	Cmbt_HMCvr,
	Cmbt_HMFire,
	Cmbt_HMFlnk,
	Cmbt_HMHeadPopr,
	Cmbt_HMKll,
	Cmbt_HMKllCiv,
	Cmbt_HMKllName,
	Cmbt_HMKllPrpTss,
	Cmbt_HMMssTnt,
	Cmbt_HMShrpShtr,
	Cmbt_HMSpttd,
	Cmbt_HMVnshd,
	Cmbt_Hold,
	Cmbt_HoldLdr,
	Cmbt_HumShldRls1,
	Cmbt_HumShldRls2,
	Cmbt_HumShldRls3,
	Cmbt_HumShldRlsFem1,
	Cmbt_HumShldRlsFem2,
	Cmbt_HumShldRlsFem3,
	Cmbt_HumShldVctm,
	Cmbt_HumShldLdr,
	Cmbt_LngLst,
	Cmbt_LngLstRsp,
	Cmbt_LstMnStn,
	Cmbt_LstSght,
	Cmbt_LstSghtRsp,
	Cmbt_NdrAttck,
	Cmbt_Relod,
	Cmbt_Scrm,
	Cmbt_ThrowFlash,
	Cmbt_ThrowFlashMiss,
	Cmbt_ThrowFlashMiss2,
	Cmbt_ThrowFlashWin,
	Cmbt_ThrowFlashWin2,
	Cmbt_TkDwnLdr,
	Cmbt_VntAck,
	Cmbt_Whmp,
	Cmbt_StalemateHold,
	Cmbt_StalemateTnt,
	Cmbt_TriggerTheAlarm,
	Cmbt_47Mpty,
	Cmbt_47SuperSize,
	Evac_PrtTrgtSolo,
	Evac_PrtTrgtAck,
	Evac_PrtTrgtAckLdr,
	Evac_PrtTrgtEscrt,
	Evac_PrtTrgtStop,
	Evac_PrtTrgtStnd,
	Evac_PrtTrgtStndRsp,
	Evac_Cornered,
	Evac_MovOut,
	Evac_PathChange,
	Evac_PeelOff,
	Evac_LastPeelOff,
	Evac_ShltrArrv,
	Evac_ShltrBad,
	Evac_ShltrLdr,
	Evac_ShltrRsp,
	Evac_TrgtHitRsp,
	AvoidXplo_Ack,
	AvoidXplo_Stnd,
	Ar_47BadAction,
	Ar_47X,
	Ar_BadDsg,
	Ar_BlmeKll,
	Ar_BlameKnckDwn,
	Ar_BlameKnckDwnPT,
	Ar_BlameKllPT,
	Ar_47BadActionPT,
	Ar_DrgBody,
	Ar_FkeSrrdrTnt,
	Ar_HMDoor,
	Ar_Strangle,
	Ar_Trspss,
	Ar_WeapWrn1,
	Ar_WeapWrn2,
	Ar_Wrn1,
	Ar_Wrn2,
	Ar_Wrn3,
	Ar_VictimAck,
	Ar_Thief,
	Ar_Rsp,
	Sniper_Ack,
	InCa_BackupCll,
	InCa_ChckCvr,
	InCa_CivRptFail,
	InCa_CivUpset,
	InCa_ClstTnt,
	InCa_HMTnt,
	InCa_Idle,
	InCa_NitiateHMKnwn,
	InCa_SrchLdr,
	InCa_Stnd,
	InCa_StndAgtd,
	InCa_StndAgtdLdr,
	InCa_StndAgtdHMKnwn,
	InCa_StndAgtdHMKnwnLdr,
	InCa_StndHMKnwn,
	InCa_StndHMKnwnLdr,
	InCa_StndLdr,
	InCa_StndRsp,
	InCa_StndLckDwnFlsAlrm,
	InCa_VntTnt,
	InCa_Brk2Civ,
	InCa_Brk2Grd,
	InCa_Brk2Rdo,
	InCa_BrkAsk,
	InCa_GhostAsk,
	InCa_TriggerTheAlarm,
	InCa_Xpln47Thief,
	InCa_DstrssInv,
	InCa_DstrssLdr,
	InCa_DstrssInvLdr,
	InCa_WakeAsk,
	InCa_47Rcall,
	InCa_WakerStnd,
	InCa_ClsCmbtAck,
	InCa_SeeDthInv,
	InCa_SeeDthInvLdr,
	InCa_SeeDthLdr,
	InCa_XploInv,
	InCa_XploInvLdr,
	InCa_XploLdr,
	InCa_AlarmAck,
	InCa_GnShtInv,
	InCa_GnShtInvLdr,
	InCa_GnShtLdr,
	InCa_RecurSvrInv,
	InCa_RecurSvrInvLdr,
	InCa_RecurSvrInvRsp,
	InCa_RecurSvrLdr,
	InCa_RecurSvrRsp,
	InCa_LckDwnGtOutLdr,
	InCa_LckDwnGtOutRsp,
	InCa_LckDwnWrn1,
	InCa_LckDwnWrn2,
	InCa_LckDwnWrn3,
	InCa_LckDwnCivCmnt,
	InCa_FrskAck,
	InCa_Frsk,
	InCa_FrskCln,
	InCa_FrskWpn,
	InCa_Xpln47Wpn,
	InCa_XplnAccdnt,
	InCa_XplnDedBdy,
	InCa_XplnDedBdyMassive,
	InCa_XplnDrgBdy,
	InCa_XplnDstrss,
	InCa_XplnExplo,
	InCa_XplnGhost,
	InCa_XplnGnsht,
	InCa_XplnNkdBdy,
	InCa_XplnPcfdBdy,
	InCa_XplnSeeDth,
	InCa_XplnTrspss,
	InCa_XplnX,
	InCa_XplnWpn,
	InCa_XplnDsg,
	InCa_XplnImposter,
	InCa_XplnRecurSvr,
	InCa_XplnRsp,
	InCa_XplnAckRdo,
	InCa_XplnKnckDwn,
	InCa_XplnKnckDwnVctm,
	InCa_XplnKnckDwnGhost,
	InCa_XplnSeeStrngl,
	InCa_XplnHuntTargetWin,
	InCa_XplnHuntTargetFail,
	InCa_VIPDownAck,
	InCa_VIPKillAck,
	Accdnt_Inv,
	InDedBdy_BloodPllAck,
	InDedBdy_Ack,
	InDedBdy_NkdAck,
	InDedBdy_Inv,
	InDedBdy_BllPllRpt,
	InDedBdy_Massive,
	InDedBdy_PcfdInv,
	InDedBdy_CntnAck,
	InDedBdy_Stnd,
	InDedBdy_CircleBdy,
	InDedBdy_CivCmnt,
	InDedBdy_PrmtrBrchWrn1,
	InDedBdy_PrmtrBrchWrn2,
	InDedBdy_47AsGrdAck,
	InDedBdy_BodyGone,
	InDedBdy_VctmRcvr,
	InDedBdy_WakerWake,
	InDedBdy_WakeRsp,
	InDedBdy_WakeNkdLdr,
	InDedBdy_WakeNkdRsp,
	Rcvr_Xpln47,
	Rcvr_XplnDsg,
	Rcvr_XplnKnckDwn,
	InDsg_FllwWrn1,
	InDsg_FllwWrn2,
	InDsg_FllwWrn3,
	InDsg_Pzzl,
	InDsg_Stnd,
	InDsg_StndDistance,
	InDsg_StndHidden,
	InDsg_HdNPlnSght,
	InDsg_FllwWrn1Ack,
	InDsg_FllwWrn1BadAction,
	InDsg_FllwWrn1Wpn,
	InDsg_FllwWrn1BadSound,
	InDsg_FllwWrnJoinr,
	InDsg_FllwWrn1ShadyItem,
	Trspss_Stnd,
	Trspss_Wrn1,
	Trspss_Wrn2,
	Trspss_Wrn3,
	Trspss_Rsp,
	Trspss_SrchAckLegal47,
	Trspss_EscortAck,
	Trspss_EscortRequest,
	Trspss_EscortRequestRepeat,
	Trspss_EscortStayClose,
	Trspss_EscortOk,
	Trspss_EscortStnd,
	Trspss_EscortArrest,
	Trspss_EscortExit,
	Trspss_EscortStayRequest,
	InCu_Brk2Rdo,
	InCu_CivCmnd,
	InCu_Stnd,
	InCu_CivRsp,
	InCu_BackupRqst,
	InCu_CrAlrmAck,
	InCu_CrAlrmLdr,
	InCu_CrAlrmStndRsp,
	InCu_FtStpsAck,
	InCu_FtStpsStnd,
	InCu_PrpTssHearAck,
	InCu_PrpTssHearInv,
	InCu_PrpTssHearLdr,
	InCu_PrpTssHearStndRsp,
	InCu_PrpTssSeeAck,
	InCu_PrpTssSeeInv,
	InCu_PrpTssSeeLdr,
	InCu_PrpTssSeeStndRsp,
	InCu_RdoAck,
	InCu_RdoInv,
	InCu_RdoLdr,
	InCu_RdoStndRsp,
	InCu_WpnInv,
	InCu_RecurAck,
	InCu_RecurInv,
	InCu_RecurLdr,
	InCu_RecurRsp,
	InCu_ItemAckLdr,
	InCu_CrAlrmStndStndRsp,
	InCu_EscrtTrgtRedLight,
	InCu_EscrtTrgtGreenLight,
	InSt_HMAglty,
	InSt_HMBz,
	InSt_HMBzStnd,
	InSt_HMEntXit,
	InSt_HMInCvr,
	InSt_HMSnkng,
	InSt_PrpTssSee,
	InSt_Stnd,
	InSt_Wrn,
	InSt_HM2Cls,
	InSt_SickAck,
	InSt_AdiosRequest,
	InSt_PQ,
	FseBx_Fixed,
	FseBx_Fixing,
	FseBx_GoFix,
	FseBx_SabAck,
	Sentry_DenyEntry,
	Sentry_Frsk,
	Sentry_FrskRequest,
	Sentry_ItemRequest,
	Sentry_Accepted,
	Sentry_FrskWpnAck,
	Sentry_47LoiterAck,
	Sentry_DenyDsg,
	Sentry_PostCommentLdr,
	Sentry_PostCommentRsp,
	VIP_MssgnA_Ldr,
	VIP_MssgnB_Rsp,
	VIP_MssgnC_Ldr,
	VIP_MssgnD_Rsp,
	VIP_MssngCallOut,
	Dth_Sick,
	Dth_Poison,
	Gen_Avoid,
	Gen_CloseCall,
	Gen_PhnPckUP,
	Gen_PhoneActLockdown,
	Cmbt_FlushOutLdr,
	Cmbt_HMPrptssKnckOut,
	InCa_FrskHeadsUpLdr,
	InCa_FrskHeadsUpRdo,
	InCa_XplnLOS,
	InCa_XplnGotShot,
	InDedBdy_CivCmntPhone,
	InDedBdy_NoFaulVctmXpln,
	InDsg_FllwWrn1Nkd,
	Ar_BlameKnckDwnMelee,
	Exp_Carry,
	Exp_ClearThroat,
	Exp_Cough,
	Exp_Drink,
	Exp_Exhale,
	Exp_Idle,
	Exp_Inhale,
	Exp_InhaleFast,
	Exp_Sniff,
	Exp_Swallow,
	Exp_Think,
	Exp_Scared,
	Exp_Gld,
	Exp_Dsppntd,
	Exp_InPain,
	InCa_AckBdy,
	InCa_AckBdyLdr,
	InDedBdy_CivCmntPcfd,
	InDedBdy_CivCmntPhonePcfd,
	Gen_SocialAck
}

impl Display for SoundDefinition {
	fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
		std::fmt::Debug::fmt(&self, f)
	}
}

static H2_DEFINITIONS: [SoundDefinition; 424] = [
	SoundDefinition::_NoSound,
	SoundDefinition::Dth_BrkNck,
	SoundDefinition::Dth_Fll,
	SoundDefinition::Dth_GnSht,
	SoundDefinition::Dth_HdSht,
	SoundDefinition::Dth_Mpct,
	SoundDefinition::Dth_SltThrt,
	SoundDefinition::Dth_Strngl,
	SoundDefinition::Dth_Xplo,
	SoundDefinition::Dth_PrpF,
	SoundDefinition::Dth_Electro,
	SoundDefinition::Dth_Burn,
	SoundDefinition::Dth_Crush,
	SoundDefinition::Dth_Scrm,
	SoundDefinition::Dth_Hrt,
	SoundDefinition::Dth_SrpsGrab,
	SoundDefinition::Dth_HumShldStrain,
	SoundDefinition::Dth_Snore,
	SoundDefinition::Dth_Groan,
	SoundDefinition::Dth_Dump,
	SoundDefinition::Dth_PrpTssFrntAck,
	SoundDefinition::Dth_Headlock,
	SoundDefinition::Dth_Blinded,
	SoundDefinition::Dth_BeeSting,
	SoundDefinition::Gen_Grt47,
	SoundDefinition::Gen_GrtGrd47WGun,
	SoundDefinition::Gen_GrtTrgt,
	SoundDefinition::Gen_GrtTrgtRsp,
	SoundDefinition::Gen_NPC2NPCGrt,
	SoundDefinition::Gen_NPC2NPCRsp,
	SoundDefinition::Gen_GtHlp,
	SoundDefinition::Gen_GtHlpLd,
	SoundDefinition::Gen_GtHlp47Knwn,
	SoundDefinition::Gen_Mssng,
	SoundDefinition::Gen_HMHere,
	SoundDefinition::Gen_HMThere,
	SoundDefinition::Gen_SrpsLow,
	SoundDefinition::Gen_SrpsLowShort,
	SoundDefinition::Gen_Srps,
	SoundDefinition::Gen_SrpsLd,
	SoundDefinition::Gen_StndRsp,
	SoundDefinition::Gen_Stop,
	SoundDefinition::Gen_StopLd,
	SoundDefinition::Gen_Reveal,
	SoundDefinition::Gen_ThumbsUp,
	SoundDefinition::Gen_BrknAck,
	SoundDefinition::Gen_Ack,
	SoundDefinition::Gen_AckLd,
	SoundDefinition::Gen_AckNtnse,
	SoundDefinition::Gen_BumpAck,
	SoundDefinition::Gen_Curse,
	SoundDefinition::Gen_CurseLow,
	SoundDefinition::Gen_DrpGun,
	SoundDefinition::Gen_DrpCase,
	SoundDefinition::Gen_CoinCurse,
	SoundDefinition::Gen_TransportGreet,
	SoundDefinition::Gen_Thanks,
	SoundDefinition::Gen_ReturnItem2Guard,
	SoundDefinition::Gen_NoWay1,
	SoundDefinition::Gen_NoWay2Kidding,
	SoundDefinition::Gen_NoWay3Joke,
	SoundDefinition::Gen_NoWay44Real,
	SoundDefinition::Gen_NoWay5DntBeliv,
	SoundDefinition::Gen_NoWay6Serious,
	SoundDefinition::Gen_NoWay7Horrible,
	SoundDefinition::Gen_Way1,
	SoundDefinition::Gen_Way2Kidding,
	SoundDefinition::Gen_Way3Joke,
	SoundDefinition::Gen_Way44Real,
	SoundDefinition::Gen_Way5DntBeliv,
	SoundDefinition::Gen_Way6Serious,
	SoundDefinition::Gen_Way7Horrible,
	SoundDefinition::Gen_NkdRunAck,
	SoundDefinition::Gen_Grasp,
	SoundDefinition::Gen_Amused,
	SoundDefinition::Gen_Annoyed,
	SoundDefinition::Gen_BdygrdArrive,
	SoundDefinition::Gen_BdygrdMovOut,
	SoundDefinition::Gen_GiveUp,
	SoundDefinition::Gen_Off,
	SoundDefinition::Gen_On,
	SoundDefinition::Gen_PanicLow,
	SoundDefinition::Gen_Sick,
	SoundDefinition::Gen_SmellAck,
	SoundDefinition::Gen_SmrtPhnAct,
	SoundDefinition::Gen_PhoneAct,
	SoundDefinition::Gen_OutbreakInfect,
	SoundDefinition::Gen_OutbreakSick,
	SoundDefinition::Gen_OutbreakWhine,
	SoundDefinition::Gtag,
	SoundDefinition::ClsCmbt_Ack,
	SoundDefinition::ClsCmbt_Tnt,
	SoundDefinition::Cmbt_BackupCll,
	SoundDefinition::Cmbt_BadDsg,
	SoundDefinition::Cmbt_Beg,
	SoundDefinition::Cmbt_ClsAck,
	SoundDefinition::Cmbt_Fire,
	SoundDefinition::Cmbt_FireLdr,
	SoundDefinition::Cmbt_GtHit,
	SoundDefinition::Cmbt_HitHM,
	SoundDefinition::Cmbt_HMClsCmbtAck,
	SoundDefinition::Cmbt_HMCvr,
	SoundDefinition::Cmbt_HMFire,
	SoundDefinition::Cmbt_HMFlnk,
	SoundDefinition::Cmbt_HMHeadPopr,
	SoundDefinition::Cmbt_HMKll,
	SoundDefinition::Cmbt_HMKllCiv,
	SoundDefinition::Cmbt_HMKllName,
	SoundDefinition::Cmbt_HMKllPrpTss,
	SoundDefinition::Cmbt_HMMssTnt,
	SoundDefinition::Cmbt_HMShrpShtr,
	SoundDefinition::Cmbt_HMSpttd,
	SoundDefinition::Cmbt_HMVnshd,
	SoundDefinition::Cmbt_Hold,
	SoundDefinition::Cmbt_HoldLdr,
	SoundDefinition::Cmbt_HumShldRls1,
	SoundDefinition::Cmbt_HumShldRls2,
	SoundDefinition::Cmbt_HumShldRls3,
	SoundDefinition::Cmbt_HumShldRlsFem1,
	SoundDefinition::Cmbt_HumShldRlsFem2,
	SoundDefinition::Cmbt_HumShldRlsFem3,
	SoundDefinition::Cmbt_HumShldVctm,
	SoundDefinition::Cmbt_HumShldLdr,
	SoundDefinition::Cmbt_LngLst,
	SoundDefinition::Cmbt_LngLstRsp,
	SoundDefinition::Cmbt_LstMnStn,
	SoundDefinition::Cmbt_LstSght,
	SoundDefinition::Cmbt_LstSghtRsp,
	SoundDefinition::Cmbt_NdrAttck,
	SoundDefinition::Cmbt_Relod,
	SoundDefinition::Cmbt_Scrm,
	SoundDefinition::Cmbt_ThrowFlash,
	SoundDefinition::Cmbt_ThrowFlashMiss,
	SoundDefinition::Cmbt_ThrowFlashMiss2,
	SoundDefinition::Cmbt_ThrowFlashWin,
	SoundDefinition::Cmbt_ThrowFlashWin2,
	SoundDefinition::Cmbt_TkDwnLdr,
	SoundDefinition::Cmbt_VntAck,
	SoundDefinition::Cmbt_Whmp,
	SoundDefinition::Cmbt_StalemateHold,
	SoundDefinition::Cmbt_StalemateTnt,
	SoundDefinition::Cmbt_TriggerTheAlarm,
	SoundDefinition::Cmbt_47Mpty,
	SoundDefinition::Cmbt_47SuperSize,
	SoundDefinition::Evac_PrtTrgtSolo,
	SoundDefinition::Evac_PrtTrgtAck,
	SoundDefinition::Evac_PrtTrgtAckLdr,
	SoundDefinition::Evac_PrtTrgtEscrt,
	SoundDefinition::Evac_PrtTrgtStop,
	SoundDefinition::Evac_PrtTrgtStnd,
	SoundDefinition::Evac_PrtTrgtStndRsp,
	SoundDefinition::Evac_Cornered,
	SoundDefinition::Evac_MovOut,
	SoundDefinition::Evac_PathChange,
	SoundDefinition::Evac_PeelOff,
	SoundDefinition::Evac_LastPeelOff,
	SoundDefinition::Evac_ShltrArrv,
	SoundDefinition::Evac_ShltrBad,
	SoundDefinition::Evac_ShltrLdr,
	SoundDefinition::Evac_ShltrRsp,
	SoundDefinition::Evac_TrgtHitRsp,
	SoundDefinition::AvoidXplo_Ack,
	SoundDefinition::AvoidXplo_Stnd,
	SoundDefinition::Ar_47BadAction,
	SoundDefinition::Ar_47X,
	SoundDefinition::Ar_BadDsg,
	SoundDefinition::Ar_BlmeKll,
	SoundDefinition::Ar_BlameKnckDwn,
	SoundDefinition::Ar_BlameKnckDwnPT,
	SoundDefinition::Ar_BlameKllPT,
	SoundDefinition::Ar_47BadActionPT,
	SoundDefinition::Ar_DrgBody,
	SoundDefinition::Ar_FkeSrrdrTnt,
	SoundDefinition::Ar_HMDoor,
	SoundDefinition::Ar_Strangle,
	SoundDefinition::Ar_Trspss,
	SoundDefinition::Ar_WeapWrn1,
	SoundDefinition::Ar_WeapWrn2,
	SoundDefinition::Ar_Wrn1,
	SoundDefinition::Ar_Wrn2,
	SoundDefinition::Ar_Wrn3,
	SoundDefinition::Ar_VictimAck,
	SoundDefinition::Ar_Thief,
	SoundDefinition::Ar_Rsp,
	SoundDefinition::Sniper_Ack,
	SoundDefinition::InCa_BackupCll,
	SoundDefinition::InCa_ChckCvr,
	SoundDefinition::InCa_CivRptFail,
	SoundDefinition::InCa_CivUpset,
	SoundDefinition::InCa_ClstTnt,
	SoundDefinition::InCa_HMTnt,
	SoundDefinition::InCa_Idle,
	SoundDefinition::InCa_NitiateHMKnwn,
	SoundDefinition::InCa_SrchLdr,
	SoundDefinition::InCa_Stnd,
	SoundDefinition::InCa_StndAgtd,
	SoundDefinition::InCa_StndAgtdLdr,
	SoundDefinition::InCa_StndAgtdHMKnwn,
	SoundDefinition::InCa_StndAgtdHMKnwnLdr,
	SoundDefinition::InCa_StndHMKnwn,
	SoundDefinition::InCa_StndHMKnwnLdr,
	SoundDefinition::InCa_StndLdr,
	SoundDefinition::InCa_StndRsp,
	SoundDefinition::InCa_StndLckDwnFlsAlrm,
	SoundDefinition::InCa_VntTnt,
	SoundDefinition::InCa_Brk2Civ,
	SoundDefinition::InCa_Brk2Grd,
	SoundDefinition::InCa_Brk2Rdo,
	SoundDefinition::InCa_BrkAsk,
	SoundDefinition::InCa_GhostAsk,
	SoundDefinition::InCa_TriggerTheAlarm,
	SoundDefinition::InCa_Xpln47Thief,
	SoundDefinition::InCa_DstrssInv,
	SoundDefinition::InCa_DstrssLdr,
	SoundDefinition::InCa_DstrssInvLdr,
	SoundDefinition::InCa_WakeAsk,
	SoundDefinition::InCa_47Rcall,
	SoundDefinition::InCa_WakerStnd,
	SoundDefinition::InCa_ClsCmbtAck,
	SoundDefinition::InCa_SeeDthInv,
	SoundDefinition::InCa_SeeDthInvLdr,
	SoundDefinition::InCa_SeeDthLdr,
	SoundDefinition::InCa_XploInv,
	SoundDefinition::InCa_XploInvLdr,
	SoundDefinition::InCa_XploLdr,
	SoundDefinition::InCa_AlarmAck,
	SoundDefinition::InCa_GnShtInv,
	SoundDefinition::InCa_GnShtInvLdr,
	SoundDefinition::InCa_GnShtLdr,
	SoundDefinition::InCa_RecurSvrInv,
	SoundDefinition::InCa_RecurSvrInvLdr,
	SoundDefinition::InCa_RecurSvrInvRsp,
	SoundDefinition::InCa_RecurSvrLdr,
	SoundDefinition::InCa_RecurSvrRsp,
	SoundDefinition::InCa_LckDwnGtOutLdr,
	SoundDefinition::InCa_LckDwnGtOutRsp,
	SoundDefinition::InCa_LckDwnWrn1,
	SoundDefinition::InCa_LckDwnWrn2,
	SoundDefinition::InCa_LckDwnWrn3,
	SoundDefinition::InCa_LckDwnCivCmnt,
	SoundDefinition::InCa_FrskAck,
	SoundDefinition::InCa_Frsk,
	SoundDefinition::InCa_FrskCln,
	SoundDefinition::InCa_FrskWpn,
	SoundDefinition::InCa_Xpln47Wpn,
	SoundDefinition::InCa_XplnAccdnt,
	SoundDefinition::InCa_XplnDedBdy,
	SoundDefinition::InCa_XplnDedBdyMassive,
	SoundDefinition::InCa_XplnDrgBdy,
	SoundDefinition::InCa_XplnDstrss,
	SoundDefinition::InCa_XplnExplo,
	SoundDefinition::InCa_XplnGhost,
	SoundDefinition::InCa_XplnGnsht,
	SoundDefinition::InCa_XplnNkdBdy,
	SoundDefinition::InCa_XplnPcfdBdy,
	SoundDefinition::InCa_XplnSeeDth,
	SoundDefinition::InCa_XplnTrspss,
	SoundDefinition::InCa_XplnX,
	SoundDefinition::InCa_XplnWpn,
	SoundDefinition::InCa_XplnDsg,
	SoundDefinition::InCa_XplnImposter,
	SoundDefinition::InCa_XplnRecurSvr,
	SoundDefinition::InCa_XplnRsp,
	SoundDefinition::InCa_XplnAckRdo,
	SoundDefinition::InCa_XplnKnckDwn,
	SoundDefinition::InCa_XplnKnckDwnVctm,
	SoundDefinition::InCa_XplnKnckDwnGhost,
	SoundDefinition::InCa_XplnSeeStrngl,
	SoundDefinition::InCa_XplnHuntTargetWin,
	SoundDefinition::InCa_XplnHuntTargetFail,
	SoundDefinition::InCa_VIPDownAck,
	SoundDefinition::InCa_VIPKillAck,
	SoundDefinition::Accdnt_Inv,
	SoundDefinition::InDedBdy_BloodPllAck,
	SoundDefinition::InDedBdy_Ack,
	SoundDefinition::InDedBdy_NkdAck,
	SoundDefinition::InDedBdy_Inv,
	SoundDefinition::InDedBdy_BllPllRpt,
	SoundDefinition::InDedBdy_Massive,
	SoundDefinition::InDedBdy_PcfdInv,
	SoundDefinition::InDedBdy_CntnAck,
	SoundDefinition::InDedBdy_Stnd,
	SoundDefinition::InDedBdy_CircleBdy,
	SoundDefinition::InDedBdy_CivCmnt,
	SoundDefinition::InDedBdy_PrmtrBrchWrn1,
	SoundDefinition::InDedBdy_PrmtrBrchWrn2,
	SoundDefinition::InDedBdy_47AsGrdAck,
	SoundDefinition::InDedBdy_BodyGone,
	SoundDefinition::InDedBdy_VctmRcvr,
	SoundDefinition::InDedBdy_WakerWake,
	SoundDefinition::InDedBdy_WakeRsp,
	SoundDefinition::InDedBdy_WakeNkdLdr,
	SoundDefinition::InDedBdy_WakeNkdRsp,
	SoundDefinition::Rcvr_Xpln47,
	SoundDefinition::Rcvr_XplnDsg,
	SoundDefinition::Rcvr_XplnKnckDwn,
	SoundDefinition::InDsg_FllwWrn1,
	SoundDefinition::InDsg_FllwWrn2,
	SoundDefinition::InDsg_FllwWrn3,
	SoundDefinition::InDsg_Pzzl,
	SoundDefinition::InDsg_Stnd,
	SoundDefinition::InDsg_StndDistance,
	SoundDefinition::InDsg_StndHidden,
	SoundDefinition::InDsg_HdNPlnSght,
	SoundDefinition::InDsg_FllwWrn1Ack,
	SoundDefinition::InDsg_FllwWrn1BadAction,
	SoundDefinition::InDsg_FllwWrn1Wpn,
	SoundDefinition::InDsg_FllwWrn1BadSound,
	SoundDefinition::InDsg_FllwWrnJoinr,
	SoundDefinition::InDsg_FllwWrn1ShadyItem,
	SoundDefinition::Trspss_Stnd,
	SoundDefinition::Trspss_Wrn1,
	SoundDefinition::Trspss_Wrn2,
	SoundDefinition::Trspss_Wrn3,
	SoundDefinition::Trspss_Rsp,
	SoundDefinition::Trspss_SrchAckLegal47,
	SoundDefinition::Trspss_EscortAck,
	SoundDefinition::Trspss_EscortRequest,
	SoundDefinition::Trspss_EscortRequestRepeat,
	SoundDefinition::Trspss_EscortStayClose,
	SoundDefinition::Trspss_EscortOk,
	SoundDefinition::Trspss_EscortStnd,
	SoundDefinition::Trspss_EscortArrest,
	SoundDefinition::Trspss_EscortExit,
	SoundDefinition::Trspss_EscortStayRequest,
	SoundDefinition::InCu_Brk2Rdo,
	SoundDefinition::InCu_CivCmnd,
	SoundDefinition::InCu_Stnd,
	SoundDefinition::InCu_CivRsp,
	SoundDefinition::InCu_BackupRqst,
	SoundDefinition::InCu_CrAlrmAck,
	SoundDefinition::InCu_CrAlrmLdr,
	SoundDefinition::InCu_CrAlrmStndRsp,
	SoundDefinition::InCu_FtStpsAck,
	SoundDefinition::InCu_FtStpsStnd,
	SoundDefinition::InCu_PrpTssHearAck,
	SoundDefinition::InCu_PrpTssHearInv,
	SoundDefinition::InCu_PrpTssHearLdr,
	SoundDefinition::InCu_PrpTssHearStndRsp,
	SoundDefinition::InCu_PrpTssSeeAck,
	SoundDefinition::InCu_PrpTssSeeInv,
	SoundDefinition::InCu_PrpTssSeeLdr,
	SoundDefinition::InCu_PrpTssSeeStndRsp,
	SoundDefinition::InCu_RdoAck,
	SoundDefinition::InCu_RdoInv,
	SoundDefinition::InCu_RdoLdr,
	SoundDefinition::InCu_RdoStndRsp,
	SoundDefinition::InCu_WpnInv,
	SoundDefinition::InCu_RecurAck,
	SoundDefinition::InCu_RecurInv,
	SoundDefinition::InCu_RecurLdr,
	SoundDefinition::InCu_RecurRsp,
	SoundDefinition::InCu_ItemAckLdr,
	SoundDefinition::InCu_CrAlrmStndStndRsp,
	SoundDefinition::InCu_EscrtTrgtRedLight,
	SoundDefinition::InCu_EscrtTrgtGreenLight,
	SoundDefinition::InSt_HMAglty,
	SoundDefinition::InSt_HMBz,
	SoundDefinition::InSt_HMBzStnd,
	SoundDefinition::InSt_HMEntXit,
	SoundDefinition::InSt_HMInCvr,
	SoundDefinition::InSt_HMSnkng,
	SoundDefinition::InSt_PrpTssSee,
	SoundDefinition::InSt_Stnd,
	SoundDefinition::InSt_Wrn,
	SoundDefinition::InSt_HM2Cls,
	SoundDefinition::InSt_SickAck,
	SoundDefinition::InSt_AdiosRequest,
	SoundDefinition::InSt_PQ,
	SoundDefinition::FseBx_Fixed,
	SoundDefinition::FseBx_Fixing,
	SoundDefinition::FseBx_GoFix,
	SoundDefinition::FseBx_SabAck,
	SoundDefinition::Sentry_DenyEntry,
	SoundDefinition::Sentry_Frsk,
	SoundDefinition::Sentry_FrskRequest,
	SoundDefinition::Sentry_ItemRequest,
	SoundDefinition::Sentry_Accepted,
	SoundDefinition::Sentry_FrskWpnAck,
	SoundDefinition::Sentry_47LoiterAck,
	SoundDefinition::Sentry_DenyDsg,
	SoundDefinition::Sentry_PostCommentLdr,
	SoundDefinition::Sentry_PostCommentRsp,
	SoundDefinition::VIP_MssgnA_Ldr,
	SoundDefinition::VIP_MssgnB_Rsp,
	SoundDefinition::VIP_MssgnC_Ldr,
	SoundDefinition::VIP_MssgnD_Rsp,
	SoundDefinition::VIP_MssngCallOut,
	SoundDefinition::Dth_Sick,
	SoundDefinition::Dth_Poison,
	SoundDefinition::Gen_Avoid,
	SoundDefinition::Gen_CloseCall,
	SoundDefinition::Gen_PhnPckUP,
	SoundDefinition::Gen_PhoneActLockdown,
	SoundDefinition::Cmbt_FlushOutLdr,
	SoundDefinition::Cmbt_HMPrptssKnckOut,
	SoundDefinition::InCa_FrskHeadsUpLdr,
	SoundDefinition::InCa_FrskHeadsUpRdo,
	SoundDefinition::InCa_XplnLOS,
	SoundDefinition::InCa_XplnGotShot,
	SoundDefinition::InDedBdy_CivCmntPhone,
	SoundDefinition::InDedBdy_NoFaulVctmXpln,
	SoundDefinition::InDsg_FllwWrn1Nkd,
	SoundDefinition::Ar_BlameKnckDwnMelee,
	SoundDefinition::Exp_Carry,
	SoundDefinition::Exp_ClearThroat,
	SoundDefinition::Exp_Cough,
	SoundDefinition::Exp_Drink,
	SoundDefinition::Exp_Exhale,
	SoundDefinition::Exp_Idle,
	SoundDefinition::Exp_Inhale,
	SoundDefinition::Exp_InhaleFast,
	SoundDefinition::Exp_Sniff,
	SoundDefinition::Exp_Swallow,
	SoundDefinition::Exp_Think,
	SoundDefinition::Exp_Scared,
	SoundDefinition::Exp_Gld,
	SoundDefinition::Exp_Dsppntd,
	SoundDefinition::Exp_InPain,
	SoundDefinition::InCa_AckBdy,
	SoundDefinition::InCa_AckBdyLdr,
	SoundDefinition::InDedBdy_CivCmntPcfd,
	SoundDefinition::InDedBdy_CivCmntPhonePcfd,
	SoundDefinition::Gen_SocialAck
];

static H1_DEFINITIONS: [SoundDefinition; 409] = [
	SoundDefinition::_NoSound,
	SoundDefinition::Dth_BrkNck,
	SoundDefinition::Dth_Fll,
	SoundDefinition::Dth_GnSht,
	SoundDefinition::Dth_HdSht,
	SoundDefinition::Dth_Mpct,
	SoundDefinition::Dth_SltThrt,
	SoundDefinition::Dth_Strngl,
	SoundDefinition::Dth_Xplo,
	SoundDefinition::Dth_PrpF,
	SoundDefinition::Dth_Electro,
	SoundDefinition::Dth_Burn,
	SoundDefinition::Dth_Crush,
	SoundDefinition::Dth_Scrm,
	SoundDefinition::Dth_Hrt,
	SoundDefinition::Dth_SrpsGrab,
	SoundDefinition::Dth_HumShldStrain,
	SoundDefinition::Dth_Snore,
	SoundDefinition::Dth_Groan,
	SoundDefinition::Dth_Dump,
	SoundDefinition::Dth_PrpTssFrntAck,
	SoundDefinition::Dth_Headlock,
	SoundDefinition::Gen_Grt47,
	SoundDefinition::Gen_GrtGrd47WGun,
	SoundDefinition::Gen_GrtTrgt,
	SoundDefinition::Gen_GrtTrgtRsp,
	SoundDefinition::Gen_NPC2NPCGrt,
	SoundDefinition::Gen_NPC2NPCRsp,
	SoundDefinition::Gen_GtHlp,
	SoundDefinition::Gen_GtHlpLd,
	SoundDefinition::Gen_GtHlp47Knwn,
	SoundDefinition::Gen_Mssng,
	SoundDefinition::Gen_HMHere,
	SoundDefinition::Gen_HMThere,
	SoundDefinition::Gen_SrpsLow,
	SoundDefinition::Gen_SrpsLowShort,
	SoundDefinition::Gen_Srps,
	SoundDefinition::Gen_SrpsLd,
	SoundDefinition::Gen_StndRsp,
	SoundDefinition::Gen_Stop,
	SoundDefinition::Gen_StopLd,
	SoundDefinition::Gen_Reveal,
	SoundDefinition::Gen_ThumbsUp,
	SoundDefinition::Gen_BrknAck,
	SoundDefinition::Gen_Ack,
	SoundDefinition::Gen_AckLd,
	SoundDefinition::Gen_AckNtnse,
	SoundDefinition::Gen_BumpAck,
	SoundDefinition::Gen_Curse,
	SoundDefinition::Gen_CurseLow,
	SoundDefinition::Gen_DrpGun,
	SoundDefinition::Gen_DrpCase,
	SoundDefinition::Gen_CoinCurse,
	SoundDefinition::Gen_TransportGreet,
	SoundDefinition::Gen_NoWay1,
	SoundDefinition::Gen_NoWay2Kidding,
	SoundDefinition::Gen_NoWay3Joke,
	SoundDefinition::Gen_NoWay44Real,
	SoundDefinition::Gen_NoWay5DntBeliv,
	SoundDefinition::Gen_NoWay6Serious,
	SoundDefinition::Gen_NoWay7Horrible,
	SoundDefinition::Gen_Way1,
	SoundDefinition::Gen_Way2Kidding,
	SoundDefinition::Gen_Way3Joke,
	SoundDefinition::Gen_Way44Real,
	SoundDefinition::Gen_Way5DntBeliv,
	SoundDefinition::Gen_Way6Serious,
	SoundDefinition::Gen_Way7Horrible,
	SoundDefinition::Gen_NkdRunAck,
	SoundDefinition::Gen_Grasp,
	SoundDefinition::Gen_Amused,
	SoundDefinition::Gen_Annoyed,
	SoundDefinition::Gen_BdygrdArrive,
	SoundDefinition::Gen_BdygrdMovOut,
	SoundDefinition::Gen_GiveUp,
	SoundDefinition::Gen_Off,
	SoundDefinition::Gen_On,
	SoundDefinition::Gen_PanicLow,
	SoundDefinition::Gen_Sick,
	SoundDefinition::Gen_SmellAck,
	SoundDefinition::Gen_SmrtPhnAct,
	SoundDefinition::Gen_PhoneAct,
	SoundDefinition::Gtag,
	SoundDefinition::ClsCmbt_Ack,
	SoundDefinition::ClsCmbt_Tnt,
	SoundDefinition::Cmbt_BackupCll,
	SoundDefinition::Cmbt_BadDsg,
	SoundDefinition::Cmbt_Beg,
	SoundDefinition::Cmbt_ClsAck,
	SoundDefinition::Cmbt_Fire,
	SoundDefinition::Cmbt_FireLdr,
	SoundDefinition::Cmbt_GtHit,
	SoundDefinition::Cmbt_HitHM,
	SoundDefinition::Cmbt_HMClsCmbtAck,
	SoundDefinition::Cmbt_HMCvr,
	SoundDefinition::Cmbt_HMFire,
	SoundDefinition::Cmbt_HMFlnk,
	SoundDefinition::Cmbt_HMHeadPopr,
	SoundDefinition::Cmbt_HMKll,
	SoundDefinition::Cmbt_HMKllCiv,
	SoundDefinition::Cmbt_HMKllName,
	SoundDefinition::Cmbt_HMKllPrpTss,
	SoundDefinition::Cmbt_HMMssTnt,
	SoundDefinition::Cmbt_HMShrpShtr,
	SoundDefinition::Cmbt_HMSpttd,
	SoundDefinition::Cmbt_HMVnshd,
	SoundDefinition::Cmbt_Hold,
	SoundDefinition::Cmbt_HoldLdr,
	SoundDefinition::Cmbt_HumShldRls1,
	SoundDefinition::Cmbt_HumShldRls2,
	SoundDefinition::Cmbt_HumShldRls3,
	SoundDefinition::Cmbt_HumShldRlsFem1,
	SoundDefinition::Cmbt_HumShldRlsFem2,
	SoundDefinition::Cmbt_HumShldRlsFem3,
	SoundDefinition::Cmbt_HumShldVctm,
	SoundDefinition::Cmbt_HumShldLdr,
	SoundDefinition::Cmbt_LngLst,
	SoundDefinition::Cmbt_LngLstRsp,
	SoundDefinition::Cmbt_LstMnStn,
	SoundDefinition::Cmbt_LstSght,
	SoundDefinition::Cmbt_LstSghtRsp,
	SoundDefinition::Cmbt_NdrAttck,
	SoundDefinition::Cmbt_Relod,
	SoundDefinition::Cmbt_Scrm,
	SoundDefinition::Cmbt_TkDwnLdr,
	SoundDefinition::Cmbt_VntAck,
	SoundDefinition::Cmbt_Whmp,
	SoundDefinition::Cmbt_StalemateHold,
	SoundDefinition::Cmbt_StalemateTnt,
	SoundDefinition::Cmbt_TriggerTheAlarm,
	SoundDefinition::Cmbt_47Mpty,
	SoundDefinition::Cmbt_47SuperSize,
	SoundDefinition::Evac_PrtTrgtSolo,
	SoundDefinition::Evac_PrtTrgtAck,
	SoundDefinition::Evac_PrtTrgtAckLdr,
	SoundDefinition::Evac_PrtTrgtEscrt,
	SoundDefinition::Evac_PrtTrgtStop,
	SoundDefinition::Evac_PrtTrgtStnd,
	SoundDefinition::Evac_PrtTrgtStndRsp,
	SoundDefinition::Evac_Cornered,
	SoundDefinition::Evac_MovOut,
	SoundDefinition::Evac_PathChange,
	SoundDefinition::Evac_PeelOff,
	SoundDefinition::Evac_LastPeelOff,
	SoundDefinition::Evac_ShltrArrv,
	SoundDefinition::Evac_ShltrBad,
	SoundDefinition::Evac_ShltrLdr,
	SoundDefinition::Evac_ShltrRsp,
	SoundDefinition::Evac_TrgtHitRsp,
	SoundDefinition::AvoidXplo_Ack,
	SoundDefinition::AvoidXplo_Stnd,
	SoundDefinition::Ar_47BadAction,
	SoundDefinition::Ar_47X,
	SoundDefinition::Ar_BadDsg,
	SoundDefinition::Ar_BlmeKll,
	SoundDefinition::Ar_BlameKnckDwn,
	SoundDefinition::Ar_BlameKnckDwnPT,
	SoundDefinition::Ar_BlameKllPT,
	SoundDefinition::Ar_47BadActionPT,
	SoundDefinition::Ar_DrgBody,
	SoundDefinition::Ar_FkeSrrdrTnt,
	SoundDefinition::Ar_HMDoor,
	SoundDefinition::Ar_Strangle,
	SoundDefinition::Ar_Trspss,
	SoundDefinition::Ar_WeapWrn1,
	SoundDefinition::Ar_WeapWrn2,
	SoundDefinition::Ar_Wrn1,
	SoundDefinition::Ar_Wrn2,
	SoundDefinition::Ar_Wrn3,
	SoundDefinition::Ar_VictimAck,
	SoundDefinition::Ar_Thief,
	SoundDefinition::Sniper_Ack,
	SoundDefinition::InCa_BackupCll,
	SoundDefinition::InCa_ChckCvr,
	SoundDefinition::InCa_CivRptFail,
	SoundDefinition::InCa_CivUpset,
	SoundDefinition::InCa_ClstTnt,
	SoundDefinition::InCa_HMTnt,
	SoundDefinition::InCa_Idle,
	SoundDefinition::InCa_NitiateHMKnwn,
	SoundDefinition::InCa_SrchLdr,
	SoundDefinition::InCa_Stnd,
	SoundDefinition::InCa_StndAgtd,
	SoundDefinition::InCa_StndAgtdLdr,
	SoundDefinition::InCa_StndAgtdHMKnwn,
	SoundDefinition::InCa_StndAgtdHMKnwnLdr,
	SoundDefinition::InCa_StndHMKnwn,
	SoundDefinition::InCa_StndHMKnwnLdr,
	SoundDefinition::InCa_StndLdr,
	SoundDefinition::InCa_StndRsp,
	SoundDefinition::InCa_StndLckDwnFlsAlrm,
	SoundDefinition::InCa_VntTnt,
	SoundDefinition::InCa_Brk2Civ,
	SoundDefinition::InCa_Brk2Grd,
	SoundDefinition::InCa_Brk2Rdo,
	SoundDefinition::InCa_BrkAsk,
	SoundDefinition::InCa_GhostAsk,
	SoundDefinition::InCa_TriggerTheAlarm,
	SoundDefinition::InCa_Xpln47Thief,
	SoundDefinition::InCa_DstrssInv,
	SoundDefinition::InCa_DstrssLdr,
	SoundDefinition::InCa_DstrssInvLdr,
	SoundDefinition::InCa_WakeAsk,
	SoundDefinition::InCa_47Rcall,
	SoundDefinition::InCa_WakerStnd,
	SoundDefinition::InCa_ClsCmbtAck,
	SoundDefinition::InCa_SeeDthInv,
	SoundDefinition::InCa_SeeDthInvLdr,
	SoundDefinition::InCa_SeeDthLdr,
	SoundDefinition::InCa_XploInv,
	SoundDefinition::InCa_XploInvLdr,
	SoundDefinition::InCa_XploLdr,
	SoundDefinition::InCa_AlarmAck,
	SoundDefinition::InCa_GnShtInv,
	SoundDefinition::InCa_GnShtInvLdr,
	SoundDefinition::InCa_GnShtLdr,
	SoundDefinition::InCa_RecurSvrInv,
	SoundDefinition::InCa_RecurSvrInvLdr,
	SoundDefinition::InCa_RecurSvrInvRsp,
	SoundDefinition::InCa_RecurSvrLdr,
	SoundDefinition::InCa_RecurSvrRsp,
	SoundDefinition::InCa_LckDwnGtOutLdr,
	SoundDefinition::InCa_LckDwnGtOutRsp,
	SoundDefinition::InCa_LckDwnWrn1,
	SoundDefinition::InCa_LckDwnWrn2,
	SoundDefinition::InCa_LckDwnWrn3,
	SoundDefinition::InCa_LckDwnCivCmnt,
	SoundDefinition::InCa_FrskAck,
	SoundDefinition::InCa_Frsk,
	SoundDefinition::InCa_FrskCln,
	SoundDefinition::InCa_FrskWpn,
	SoundDefinition::InCa_Xpln47Wpn,
	SoundDefinition::InCa_XplnAccdnt,
	SoundDefinition::InCa_XplnDedBdy,
	SoundDefinition::InCa_XplnDedBdyMassive,
	SoundDefinition::InCa_XplnDrgBdy,
	SoundDefinition::InCa_XplnDstrss,
	SoundDefinition::InCa_XplnExplo,
	SoundDefinition::InCa_XplnGhost,
	SoundDefinition::InCa_XplnGnsht,
	SoundDefinition::InCa_XplnNkdBdy,
	SoundDefinition::InCa_XplnPcfdBdy,
	SoundDefinition::InCa_XplnSeeDth,
	SoundDefinition::InCa_XplnTrspss,
	SoundDefinition::InCa_XplnX,
	SoundDefinition::InCa_XplnWpn,
	SoundDefinition::InCa_XplnDsg,
	SoundDefinition::InCa_XplnImposter,
	SoundDefinition::InCa_XplnRecurSvr,
	SoundDefinition::InCa_XplnRsp,
	SoundDefinition::InCa_XplnAckRdo,
	SoundDefinition::InCa_XplnKnckDwn,
	SoundDefinition::InCa_XplnKnckDwnVctm,
	SoundDefinition::InCa_XplnKnckDwnGhost,
	SoundDefinition::InCa_XplnSeeStrngl,
	SoundDefinition::InCa_XplnHuntTargetWin,
	SoundDefinition::InCa_XplnHuntTargetFail,
	SoundDefinition::InCa_VIPDownAck,
	SoundDefinition::InCa_VIPKillAck,
	SoundDefinition::Accdnt_Inv,
	SoundDefinition::InDedBdy_BloodPllAck,
	SoundDefinition::InDedBdy_Ack,
	SoundDefinition::InDedBdy_NkdAck,
	SoundDefinition::InDedBdy_Inv,
	SoundDefinition::InDedBdy_BllPllRpt,
	SoundDefinition::InDedBdy_Massive,
	SoundDefinition::InDedBdy_PcfdInv,
	SoundDefinition::InDedBdy_CntnAck,
	SoundDefinition::InDedBdy_Stnd,
	SoundDefinition::InDedBdy_CircleBdy,
	SoundDefinition::InDedBdy_CivCmnt,
	SoundDefinition::InDedBdy_PrmtrBrchWrn1,
	SoundDefinition::InDedBdy_PrmtrBrchWrn2,
	SoundDefinition::InDedBdy_47AsGrdAck,
	SoundDefinition::InDedBdy_BodyGone,
	SoundDefinition::InDedBdy_VctmRcvr,
	SoundDefinition::InDedBdy_WakerWake,
	SoundDefinition::InDedBdy_WakeRsp,
	SoundDefinition::InDedBdy_WakeNkdLdr,
	SoundDefinition::InDedBdy_WakeNkdRsp,
	SoundDefinition::Rcvr_Xpln47,
	SoundDefinition::Rcvr_XplnDsg,
	SoundDefinition::Rcvr_XplnKnckDwn,
	SoundDefinition::InDsg_FllwWrn1,
	SoundDefinition::InDsg_FllwWrn2,
	SoundDefinition::InDsg_FllwWrn3,
	SoundDefinition::InDsg_Pzzl,
	SoundDefinition::InDsg_Stnd,
	SoundDefinition::InDsg_StndDistance,
	SoundDefinition::InDsg_StndHidden,
	SoundDefinition::InDsg_HdNPlnSght,
	SoundDefinition::InDsg_FllwWrn1Ack,
	SoundDefinition::InDsg_FllwWrn1BadAction,
	SoundDefinition::InDsg_FllwWrn1Wpn,
	SoundDefinition::InDsg_FllwWrn1BadSound,
	SoundDefinition::InDsg_FllwWrnJoinr,
	SoundDefinition::InDsg_FllwWrn1ShadyItem,
	SoundDefinition::Trspss_Stnd,
	SoundDefinition::Trspss_Wrn1,
	SoundDefinition::Trspss_Wrn2,
	SoundDefinition::Trspss_Wrn3,
	SoundDefinition::Trspss_Rsp,
	SoundDefinition::Trspss_SrchAckLegal47,
	SoundDefinition::Trspss_EscortAck,
	SoundDefinition::Trspss_EscortRequest,
	SoundDefinition::Trspss_EscortRequestRepeat,
	SoundDefinition::Trspss_EscortStayClose,
	SoundDefinition::Trspss_EscortOk,
	SoundDefinition::Trspss_EscortStnd,
	SoundDefinition::Trspss_EscortArrest,
	SoundDefinition::Trspss_EscortExit,
	SoundDefinition::Trspss_EscortStayRequest,
	SoundDefinition::InCu_Brk2Rdo,
	SoundDefinition::InCu_CivCmnd,
	SoundDefinition::InCu_Stnd,
	SoundDefinition::InCu_CivRsp,
	SoundDefinition::InCu_BackupRqst,
	SoundDefinition::InCu_CrAlrmAck,
	SoundDefinition::InCu_CrAlrmLdr,
	SoundDefinition::InCu_CrAlrmStndRsp,
	SoundDefinition::InCu_FtStpsAck,
	SoundDefinition::InCu_FtStpsStnd,
	SoundDefinition::InCu_PrpTssHearAck,
	SoundDefinition::InCu_PrpTssHearInv,
	SoundDefinition::InCu_PrpTssHearLdr,
	SoundDefinition::InCu_PrpTssHearStndRsp,
	SoundDefinition::InCu_PrpTssSeeAck,
	SoundDefinition::InCu_PrpTssSeeInv,
	SoundDefinition::InCu_PrpTssSeeLdr,
	SoundDefinition::InCu_PrpTssSeeStndRsp,
	SoundDefinition::InCu_RdoAck,
	SoundDefinition::InCu_RdoInv,
	SoundDefinition::InCu_RdoLdr,
	SoundDefinition::InCu_RdoStndRsp,
	SoundDefinition::InCu_WpnInv,
	SoundDefinition::InCu_RecurAck,
	SoundDefinition::InCu_RecurInv,
	SoundDefinition::InCu_RecurLdr,
	SoundDefinition::InCu_RecurRsp,
	SoundDefinition::InCu_ItemAckLdr,
	SoundDefinition::InCu_CrAlrmStndStndRsp,
	SoundDefinition::InCu_EscrtTrgtRedLight,
	SoundDefinition::InCu_EscrtTrgtGreenLight,
	SoundDefinition::InSt_HMAglty,
	SoundDefinition::InSt_HMBz,
	SoundDefinition::InSt_HMBzStnd,
	SoundDefinition::InSt_HMEntXit,
	SoundDefinition::InSt_HMInCvr,
	SoundDefinition::InSt_HMSnkng,
	SoundDefinition::InSt_PrpTssSee,
	SoundDefinition::InSt_Stnd,
	SoundDefinition::InSt_Wrn,
	SoundDefinition::InSt_HM2Cls,
	SoundDefinition::InSt_SickAck,
	SoundDefinition::InSt_AdiosRequest,
	SoundDefinition::InSt_PQ,
	SoundDefinition::FseBx_Fixed,
	SoundDefinition::FseBx_Fixing,
	SoundDefinition::FseBx_GoFix,
	SoundDefinition::FseBx_SabAck,
	SoundDefinition::Sentry_DenyEntry,
	SoundDefinition::Sentry_Frsk,
	SoundDefinition::Sentry_FrskRequest,
	SoundDefinition::Sentry_ItemRequest,
	SoundDefinition::Sentry_Accepted,
	SoundDefinition::Sentry_FrskWpnAck,
	SoundDefinition::Sentry_47LoiterAck,
	SoundDefinition::Sentry_DenyDsg,
	SoundDefinition::VIP_MssgnA_Ldr,
	SoundDefinition::VIP_MssgnB_Rsp,
	SoundDefinition::VIP_MssgnC_Ldr,
	SoundDefinition::VIP_MssgnD_Rsp,
	SoundDefinition::VIP_MssngCallOut,
	SoundDefinition::Dth_Sick,
	SoundDefinition::Dth_Poison,
	SoundDefinition::Gen_Avoid,
	SoundDefinition::Gen_CloseCall,
	SoundDefinition::Gen_PhnPckUP,
	SoundDefinition::Gen_PhoneActLockdown,
	SoundDefinition::Cmbt_FlushOutLdr,
	SoundDefinition::Cmbt_HMPrptssKnckOut,
	SoundDefinition::InCa_FrskHeadsUpLdr,
	SoundDefinition::InCa_FrskHeadsUpRdo,
	SoundDefinition::InCa_XplnLOS,
	SoundDefinition::InCa_XplnGotShot,
	SoundDefinition::InDedBdy_CivCmntPhone,
	SoundDefinition::InDedBdy_NoFaulVctmXpln,
	SoundDefinition::InDsg_FllwWrn1Nkd,
	SoundDefinition::Ar_BlameKnckDwnMelee,
	SoundDefinition::Exp_Carry,
	SoundDefinition::Exp_ClearThroat,
	SoundDefinition::Exp_Cough,
	SoundDefinition::Exp_Drink,
	SoundDefinition::Exp_Exhale,
	SoundDefinition::Exp_Idle,
	SoundDefinition::Exp_Inhale,
	SoundDefinition::Exp_InhaleFast,
	SoundDefinition::Exp_Sniff,
	SoundDefinition::Exp_Swallow,
	SoundDefinition::Exp_Think,
	SoundDefinition::Exp_Scared,
	SoundDefinition::Exp_Gld,
	SoundDefinition::Exp_Dsppntd,
	SoundDefinition::Exp_InPain,
	SoundDefinition::InCa_AckBdy,
	SoundDefinition::InCa_AckBdyLdr,
	SoundDefinition::InDedBdy_CivCmntPcfd,
	SoundDefinition::InDedBdy_CivCmntPhonePcfd,
	SoundDefinition::Gen_SocialAck
];

impl SoundDefinition {
	#[cfg_attr(feature = "rune", rune::function(keep, path = Self::from_h3_discriminant))]
	pub fn from_h3_discriminant(discriminant: u16) -> Option<Self> {
		Self::from_discriminant(discriminant).ok()
	}

	#[cfg_attr(feature = "rune", rune::function(keep, path = Self::from_h2_discriminant))]
	pub fn from_h2_discriminant(discriminant: u16) -> Option<Self> {
		H2_DEFINITIONS.get(discriminant as usize).copied()
	}

	#[cfg_attr(feature = "rune", rune::function(keep, path = Self::from_h1_discriminant))]
	pub fn from_h1_discriminant(discriminant: u16) -> Option<Self> {
		H1_DEFINITIONS.get(discriminant as usize).copied()
	}

	#[cfg_attr(feature = "rune", rune::function(keep, instance))]
	pub fn as_h3_discriminant(&self) -> u16 {
		*self as u16
	}

	#[cfg_attr(feature = "rune", rune::function(keep, instance))]
	pub fn as_h2_discriminant(&self) -> Option<u16> {
		H2_DEFINITIONS.iter().position(|&x| x == *self).map(|x| x as u16)
	}

	#[cfg_attr(feature = "rune", rune::function(keep, instance))]
	pub fn as_h1_discriminant(&self) -> Option<u16> {
		H1_DEFINITIONS.iter().position(|&x| x == *self).map(|x| x as u16)
	}
}

impl SoundDefinitions {
	/// Parse an SDEF.
	#[try_fn]
	#[cfg_attr(feature = "rune", rune::function(keep, path = Self::parse))]
	#[cfg_attr(feature = "tracing", tracing::instrument(skip_all))]
	pub fn parse(sdef_data: &[u8], sdef_metadata: &ResourceMetadata, game_version: GameVersion) -> Result<Self> {
		let mut cursor = Cursor::new(sdef_data);

		let entries_count = u32::from_le_bytes({
			let mut x = [0u8; 4];
			cursor.read_exact(&mut x)?;
			x
		});

		let mut definitions = IndexMap::with_capacity(entries_count as usize);

		for _ in 0..entries_count {
			let definition = u32::from_le_bytes({
				let mut x = [0u8; 4];
				cursor.read_exact(&mut x)?;
				x
			});

			let dlge_index = u32::from_le_bytes({
				let mut x = [0u8; 4];
				cursor.read_exact(&mut x)?;
				x
			});

			definitions.insert(
				match game_version {
					GameVersion::H1 => SoundDefinition::from_h1_discriminant(definition as u16),
					GameVersion::H2 => SoundDefinition::from_h2_discriminant(definition as u16),
					GameVersion::H3 => SoundDefinition::from_h3_discriminant(definition as u16)
				}
				.ok_or(SdefError::InvalidSoundDefinition(definition as u16))?,
				if dlge_index != u32::MAX {
					Some(
						sdef_metadata
							.references
							.get(usize::try_from(dlge_index)?)
							.ok_or_else(|| SdefError::InvalidDependency(usize::try_from(dlge_index).unwrap()))?
							.resource
							.to_owned()
					)
				} else {
					None
				}
			);
		}

		Self {
			id: sdef_metadata.id.to_owned(),
			definitions
		}
	}

	/// Serialise this SDEF. Any definitions not existing in the given game version will be skipped.
	#[cfg_attr(feature = "rune", rune::function(keep, instance))]
	#[cfg_attr(feature = "tracing", tracing::instrument(skip_all))]
	pub fn generate(self, game_version: GameVersion) -> (Vec<u8>, ResourceMetadata) {
		let mut sdef = vec![];
		let mut metadata = ResourceMetadata {
			id: self.id,
			references: vec![],
			resource_type: "SDEF".try_into().unwrap(),
			compressed: ResourceMetadata::infer_compressed("SDEF".try_into().unwrap()),
			scrambled: ResourceMetadata::infer_scrambled("SDEF".try_into().unwrap())
		};

		sdef.extend_from_slice(&(self.definitions.len() as u32).to_le_bytes());

		for (definition, dlge) in self.definitions {
			if let Some(discrim) = match game_version {
				GameVersion::H1 => definition.as_h1_discriminant(),
				GameVersion::H2 => definition.as_h2_discriminant(),
				GameVersion::H3 => Some(definition.as_h3_discriminant())
			} {
				sdef.extend_from_slice(&(discrim as u32).to_le_bytes());

				if let Some(dlge) = dlge {
					metadata.references.push(ResourceReference {
						resource: dlge,
						flags: ReferenceFlags {
							reference_type: ReferenceType::Normal,
							acquired: false,
							..Default::default()
						}
					});

					sdef.extend_from_slice(&(metadata.references.len() as u32 - 1).to_le_bytes());
				} else {
					sdef.extend_from_slice(&u32::MAX.to_le_bytes());
				}
			}
		}

		(sdef, metadata)
	}
}
